# Generated by Django 2.2.7 on 2019-12-05 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tagcloudapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tagcloudapp.Subject')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tagcloudapp.Tag')),
            ],
            options={
                'db_table': 'subjects_tags',
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='subjects', through='tagcloudapp.SubjectTags', to='tagcloudapp.Tag'),
        ),
    ]
