# Generated by Django 2.2.7 on 2019-11-14 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tagcloudapp', '0002_auto_20191114_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='workpackage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tagcloudapp.Workpackage'),
        ),
    ]
