# Generated by Django 2.2.7 on 2019-11-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagcloudapp', '0003_auto_20191114_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='descr',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='descr',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='workpackage',
            name='descr',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
