# Generated by Django 2.2.7 on 2019-11-16 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagcloudapp', '0004_auto_20191114_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tagsize',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tagvalue',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
