# Generated by Django 2.2.7 on 2019-11-16 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagcloudapp', '0006_auto_20191116_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='tag',
            field=models.ManyToManyField(to='tagcloudapp.Tag'),
        ),
    ]
