# Generated by Django 2.2.7 on 2019-11-16 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagcloudapp', '0007_auto_20191116_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='tag',
            field=models.ManyToManyField(related_name='subjects', to='tagcloudapp.Tag'),
        ),
    ]
