# Generated by Django 2.2.7 on 2019-11-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagcloudapp', '0008_auto_20191117_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='descr',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
