# Generated by Django 2.2.7 on 2019-11-30 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagcloudapp', '0009_auto_20191130_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
