# Generated by Django 2.2.7 on 2019-11-30 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagcloudapp', '0011_auto_20191130_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='subjects', to='tagcloudapp.Tag'),
        ),
    ]
