# Generated by Django 2.2.7 on 2019-12-01 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tagcloudapp', '0015_auto_20191201_1542'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tagsubmithistory',
            table='tagsubmithistory',
        ),
    ]
